/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonMore {
        "text": string;
    }
    interface GkHoly {
    }
    interface LayoutHome {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PostCard {
        "text1": string;
        "text2": string;
        "title1": string;
    }
    interface PostComments {
        "text1": string;
        "text2": string;
    }
    interface PostDetailCard {
    }
    interface PostFooter {
        "name": string;
    }
}
declare global {
    interface HTMLButtonMoreElement extends Components.ButtonMore, HTMLStencilElement {
    }
    var HTMLButtonMoreElement: {
        prototype: HTMLButtonMoreElement;
        new (): HTMLButtonMoreElement;
    };
    interface HTMLGkHolyElement extends Components.GkHoly, HTMLStencilElement {
    }
    var HTMLGkHolyElement: {
        prototype: HTMLGkHolyElement;
        new (): HTMLGkHolyElement;
    };
    interface HTMLLayoutHomeElement extends Components.LayoutHome, HTMLStencilElement {
    }
    var HTMLLayoutHomeElement: {
        prototype: HTMLLayoutHomeElement;
        new (): HTMLLayoutHomeElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPostCardElement extends Components.PostCard, HTMLStencilElement {
    }
    var HTMLPostCardElement: {
        prototype: HTMLPostCardElement;
        new (): HTMLPostCardElement;
    };
    interface HTMLPostCommentsElement extends Components.PostComments, HTMLStencilElement {
    }
    var HTMLPostCommentsElement: {
        prototype: HTMLPostCommentsElement;
        new (): HTMLPostCommentsElement;
    };
    interface HTMLPostDetailCardElement extends Components.PostDetailCard, HTMLStencilElement {
    }
    var HTMLPostDetailCardElement: {
        prototype: HTMLPostDetailCardElement;
        new (): HTMLPostDetailCardElement;
    };
    interface HTMLPostFooterElement extends Components.PostFooter, HTMLStencilElement {
    }
    var HTMLPostFooterElement: {
        prototype: HTMLPostFooterElement;
        new (): HTMLPostFooterElement;
    };
    interface HTMLElementTagNameMap {
        "button-more": HTMLButtonMoreElement;
        "gk-holy": HTMLGkHolyElement;
        "layout-home": HTMLLayoutHomeElement;
        "my-component": HTMLMyComponentElement;
        "post-card": HTMLPostCardElement;
        "post-comments": HTMLPostCommentsElement;
        "post-detail-card": HTMLPostDetailCardElement;
        "post-footer": HTMLPostFooterElement;
    }
}
declare namespace LocalJSX {
    interface ButtonMore {
        "onClickPost"?: (event: CustomEvent<any>) => void;
        "text"?: string;
    }
    interface GkHoly {
    }
    interface LayoutHome {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PostCard {
        "text1"?: string;
        "text2"?: string;
        "title1"?: string;
    }
    interface PostComments {
        "text1"?: string;
        "text2"?: string;
    }
    interface PostDetailCard {
    }
    interface PostFooter {
        "name"?: string;
    }
    interface IntrinsicElements {
        "button-more": ButtonMore;
        "gk-holy": GkHoly;
        "layout-home": LayoutHome;
        "my-component": MyComponent;
        "post-card": PostCard;
        "post-comments": PostComments;
        "post-detail-card": PostDetailCard;
        "post-footer": PostFooter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-more": LocalJSX.ButtonMore & JSXBase.HTMLAttributes<HTMLButtonMoreElement>;
            "gk-holy": LocalJSX.GkHoly & JSXBase.HTMLAttributes<HTMLGkHolyElement>;
            "layout-home": LocalJSX.LayoutHome & JSXBase.HTMLAttributes<HTMLLayoutHomeElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "post-card": LocalJSX.PostCard & JSXBase.HTMLAttributes<HTMLPostCardElement>;
            "post-comments": LocalJSX.PostComments & JSXBase.HTMLAttributes<HTMLPostCommentsElement>;
            "post-detail-card": LocalJSX.PostDetailCard & JSXBase.HTMLAttributes<HTMLPostDetailCardElement>;
            "post-footer": LocalJSX.PostFooter & JSXBase.HTMLAttributes<HTMLPostFooterElement>;
        }
    }
}
